// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensei-res.proto

package com.sensei.search.req.protobuf;

public final class SenseiResultBPO {
  private SenseiResultBPO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Facet extends
      com.google.protobuf.GeneratedMessage {
    // Use Facet.newBuilder() to construct.
    private Facet() {
      initFields();
    }
    private Facet(boolean noInit) {}
    
    private static final Facet defaultInstance;
    public static Facet getDefaultInstance() {
      return defaultInstance;
    }
    
    public Facet getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Facet_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Facet_fieldAccessorTable;
    }
    
    // required string val = 1;
    public static final int VAL_FIELD_NUMBER = 1;
    private boolean hasVal;
    private java.lang.String val_ = "";
    public boolean hasVal() { return hasVal; }
    public java.lang.String getVal() { return val_; }
    
    // optional uint32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasVal) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVal()) {
        output.writeString(1, getVal());
      }
      if (hasCount()) {
        output.writeUInt32(2, getCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVal()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getVal());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Facet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sensei.search.req.protobuf.SenseiResultBPO.Facet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.sensei.search.req.protobuf.SenseiResultBPO.Facet result;
      
      // Construct using com.sensei.search.req.protobuf.SenseiResultBPO.Facet.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.sensei.search.req.protobuf.SenseiResultBPO.Facet();
        return builder;
      }
      
      protected com.sensei.search.req.protobuf.SenseiResultBPO.Facet internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.sensei.search.req.protobuf.SenseiResultBPO.Facet();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Facet.getDescriptor();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Facet getDefaultInstanceForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Facet.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.Facet build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.sensei.search.req.protobuf.SenseiResultBPO.Facet buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Facet buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.sensei.search.req.protobuf.SenseiResultBPO.Facet returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sensei.search.req.protobuf.SenseiResultBPO.Facet) {
          return mergeFrom((com.sensei.search.req.protobuf.SenseiResultBPO.Facet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.sensei.search.req.protobuf.SenseiResultBPO.Facet other) {
        if (other == com.sensei.search.req.protobuf.SenseiResultBPO.Facet.getDefaultInstance()) return this;
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setVal(input.readString());
              break;
            }
            case 16: {
              setCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required string val = 1;
      public boolean hasVal() {
        return result.hasVal();
      }
      public java.lang.String getVal() {
        return result.getVal();
      }
      public Builder setVal(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVal = true;
        result.val_ = value;
        return this;
      }
      public Builder clearVal() {
        result.hasVal = false;
        result.val_ = getDefaultInstance().getVal();
        return this;
      }
      
      // optional uint32 count = 2;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.sensei.search.req.protobuf.Facet)
    }
    
    static {
      defaultInstance = new Facet(true);
      com.sensei.search.req.protobuf.SenseiResultBPO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.sensei.search.req.protobuf.Facet)
  }
  
  public static final class FacetContainer extends
      com.google.protobuf.GeneratedMessage {
    // Use FacetContainer.newBuilder() to construct.
    private FacetContainer() {
      initFields();
    }
    private FacetContainer(boolean noInit) {}
    
    private static final FacetContainer defaultInstance;
    public static FacetContainer getDefaultInstance() {
      return defaultInstance;
    }
    
    public FacetContainer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_FacetContainer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_FacetContainer_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .com.sensei.search.req.protobuf.Facet facets = 2;
    public static final int FACETS_FIELD_NUMBER = 2;
    private java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Facet> facets_ =
      java.util.Collections.emptyList();
    public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Facet> getFacetsList() {
      return facets_;
    }
    public int getFacetsCount() { return facets_.size(); }
    public com.sensei.search.req.protobuf.SenseiResultBPO.Facet getFacets(int index) {
      return facets_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Facet element : getFacetsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Facet element : getFacetsList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Facet element : getFacetsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer result;
      
      // Construct using com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer();
        return builder;
      }
      
      protected com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.getDescriptor();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer getDefaultInstanceForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.facets_ != java.util.Collections.EMPTY_LIST) {
          result.facets_ =
            java.util.Collections.unmodifiableList(result.facets_);
        }
        com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer) {
          return mergeFrom((com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer other) {
        if (other == com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.facets_.isEmpty()) {
          if (result.facets_.isEmpty()) {
            result.facets_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Facet>();
          }
          result.facets_.addAll(other.facets_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              com.sensei.search.req.protobuf.SenseiResultBPO.Facet.Builder subBuilder = com.sensei.search.req.protobuf.SenseiResultBPO.Facet.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFacets(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .com.sensei.search.req.protobuf.Facet facets = 2;
      public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Facet> getFacetsList() {
        return java.util.Collections.unmodifiableList(result.facets_);
      }
      public int getFacetsCount() {
        return result.getFacetsCount();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.Facet getFacets(int index) {
        return result.getFacets(index);
      }
      public Builder setFacets(int index, com.sensei.search.req.protobuf.SenseiResultBPO.Facet value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.facets_.set(index, value);
        return this;
      }
      public Builder setFacets(int index, com.sensei.search.req.protobuf.SenseiResultBPO.Facet.Builder builderForValue) {
        result.facets_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFacets(com.sensei.search.req.protobuf.SenseiResultBPO.Facet value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.facets_.isEmpty()) {
          result.facets_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Facet>();
        }
        result.facets_.add(value);
        return this;
      }
      public Builder addFacets(com.sensei.search.req.protobuf.SenseiResultBPO.Facet.Builder builderForValue) {
        if (result.facets_.isEmpty()) {
          result.facets_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Facet>();
        }
        result.facets_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFacets(
          java.lang.Iterable<? extends com.sensei.search.req.protobuf.SenseiResultBPO.Facet> values) {
        if (result.facets_.isEmpty()) {
          result.facets_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Facet>();
        }
        super.addAll(values, result.facets_);
        return this;
      }
      public Builder clearFacets() {
        result.facets_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.sensei.search.req.protobuf.FacetContainer)
    }
    
    static {
      defaultInstance = new FacetContainer(true);
      com.sensei.search.req.protobuf.SenseiResultBPO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.sensei.search.req.protobuf.FacetContainer)
  }
  
  public static final class FieldVal extends
      com.google.protobuf.GeneratedMessage {
    // Use FieldVal.newBuilder() to construct.
    private FieldVal() {
      initFields();
    }
    private FieldVal(boolean noInit) {}
    
    private static final FieldVal defaultInstance;
    public static FieldVal getDefaultInstance() {
      return defaultInstance;
    }
    
    public FieldVal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_FieldVal_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_FieldVal_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated string vals = 2;
    public static final int VALS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> vals_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getValsList() {
      return vals_;
    }
    public int getValsCount() { return vals_.size(); }
    public java.lang.String getVals(int index) {
      return vals_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      for (java.lang.String element : getValsList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getValsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal result;
      
      // Construct using com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal();
        return builder;
      }
      
      protected com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.getDescriptor();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal getDefaultInstanceForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.vals_ != java.util.Collections.EMPTY_LIST) {
          result.vals_ =
            java.util.Collections.unmodifiableList(result.vals_);
        }
        com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal) {
          return mergeFrom((com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal other) {
        if (other == com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.vals_.isEmpty()) {
          if (result.vals_.isEmpty()) {
            result.vals_ = new java.util.ArrayList<java.lang.String>();
          }
          result.vals_.addAll(other.vals_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
            case 18: {
              addVals(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated string vals = 2;
      public java.util.List<java.lang.String> getValsList() {
        return java.util.Collections.unmodifiableList(result.vals_);
      }
      public int getValsCount() {
        return result.getValsCount();
      }
      public java.lang.String getVals(int index) {
        return result.getVals(index);
      }
      public Builder setVals(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.vals_.set(index, value);
        return this;
      }
      public Builder addVals(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.vals_.isEmpty()) {
          result.vals_ = new java.util.ArrayList<java.lang.String>();
        }
        result.vals_.add(value);
        return this;
      }
      public Builder addAllVals(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.vals_.isEmpty()) {
          result.vals_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.vals_);
        return this;
      }
      public Builder clearVals() {
        result.vals_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.sensei.search.req.protobuf.FieldVal)
    }
    
    static {
      defaultInstance = new FieldVal(true);
      com.sensei.search.req.protobuf.SenseiResultBPO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.sensei.search.req.protobuf.FieldVal)
  }
  
  public static final class Hit extends
      com.google.protobuf.GeneratedMessage {
    // Use Hit.newBuilder() to construct.
    private Hit() {
      initFields();
    }
    private Hit(boolean noInit) {}
    
    private static final Hit defaultInstance;
    public static Hit getDefaultInstance() {
      return defaultInstance;
    }
    
    public Hit getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Hit_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Hit_fieldAccessorTable;
    }
    
    // optional uint32 docid = 1;
    public static final int DOCID_FIELD_NUMBER = 1;
    private boolean hasDocid;
    private int docid_ = 0;
    public boolean hasDocid() { return hasDocid; }
    public int getDocid() { return docid_; }
    
    // optional float score = 2;
    public static final int SCORE_FIELD_NUMBER = 2;
    private boolean hasScore;
    private float score_ = 0F;
    public boolean hasScore() { return hasScore; }
    public float getScore() { return score_; }
    
    // repeated .com.sensei.search.req.protobuf.FieldVal fieldValues = 3;
    public static final int FIELDVALUES_FIELD_NUMBER = 3;
    private java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal> fieldValues_ =
      java.util.Collections.emptyList();
    public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal> getFieldValuesList() {
      return fieldValues_;
    }
    public int getFieldValuesCount() { return fieldValues_.size(); }
    public com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal getFieldValues(int index) {
      return fieldValues_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal element : getFieldValuesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDocid()) {
        output.writeUInt32(1, getDocid());
      }
      if (hasScore()) {
        output.writeFloat(2, getScore());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal element : getFieldValuesList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDocid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getDocid());
      }
      if (hasScore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getScore());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal element : getFieldValuesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Hit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sensei.search.req.protobuf.SenseiResultBPO.Hit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.sensei.search.req.protobuf.SenseiResultBPO.Hit result;
      
      // Construct using com.sensei.search.req.protobuf.SenseiResultBPO.Hit.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.sensei.search.req.protobuf.SenseiResultBPO.Hit();
        return builder;
      }
      
      protected com.sensei.search.req.protobuf.SenseiResultBPO.Hit internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.sensei.search.req.protobuf.SenseiResultBPO.Hit();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Hit.getDescriptor();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Hit getDefaultInstanceForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Hit.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.Hit build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.sensei.search.req.protobuf.SenseiResultBPO.Hit buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Hit buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.fieldValues_ != java.util.Collections.EMPTY_LIST) {
          result.fieldValues_ =
            java.util.Collections.unmodifiableList(result.fieldValues_);
        }
        com.sensei.search.req.protobuf.SenseiResultBPO.Hit returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sensei.search.req.protobuf.SenseiResultBPO.Hit) {
          return mergeFrom((com.sensei.search.req.protobuf.SenseiResultBPO.Hit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.sensei.search.req.protobuf.SenseiResultBPO.Hit other) {
        if (other == com.sensei.search.req.protobuf.SenseiResultBPO.Hit.getDefaultInstance()) return this;
        if (other.hasDocid()) {
          setDocid(other.getDocid());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (!other.fieldValues_.isEmpty()) {
          if (result.fieldValues_.isEmpty()) {
            result.fieldValues_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal>();
          }
          result.fieldValues_.addAll(other.fieldValues_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setDocid(input.readUInt32());
              break;
            }
            case 21: {
              setScore(input.readFloat());
              break;
            }
            case 26: {
              com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.Builder subBuilder = com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFieldValues(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 docid = 1;
      public boolean hasDocid() {
        return result.hasDocid();
      }
      public int getDocid() {
        return result.getDocid();
      }
      public Builder setDocid(int value) {
        result.hasDocid = true;
        result.docid_ = value;
        return this;
      }
      public Builder clearDocid() {
        result.hasDocid = false;
        result.docid_ = 0;
        return this;
      }
      
      // optional float score = 2;
      public boolean hasScore() {
        return result.hasScore();
      }
      public float getScore() {
        return result.getScore();
      }
      public Builder setScore(float value) {
        result.hasScore = true;
        result.score_ = value;
        return this;
      }
      public Builder clearScore() {
        result.hasScore = false;
        result.score_ = 0F;
        return this;
      }
      
      // repeated .com.sensei.search.req.protobuf.FieldVal fieldValues = 3;
      public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal> getFieldValuesList() {
        return java.util.Collections.unmodifiableList(result.fieldValues_);
      }
      public int getFieldValuesCount() {
        return result.getFieldValuesCount();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal getFieldValues(int index) {
        return result.getFieldValues(index);
      }
      public Builder setFieldValues(int index, com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.fieldValues_.set(index, value);
        return this;
      }
      public Builder setFieldValues(int index, com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.Builder builderForValue) {
        result.fieldValues_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFieldValues(com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.fieldValues_.isEmpty()) {
          result.fieldValues_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal>();
        }
        result.fieldValues_.add(value);
        return this;
      }
      public Builder addFieldValues(com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.Builder builderForValue) {
        if (result.fieldValues_.isEmpty()) {
          result.fieldValues_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal>();
        }
        result.fieldValues_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFieldValues(
          java.lang.Iterable<? extends com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal> values) {
        if (result.fieldValues_.isEmpty()) {
          result.fieldValues_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal>();
        }
        super.addAll(values, result.fieldValues_);
        return this;
      }
      public Builder clearFieldValues() {
        result.fieldValues_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.sensei.search.req.protobuf.Hit)
    }
    
    static {
      defaultInstance = new Hit(true);
      com.sensei.search.req.protobuf.SenseiResultBPO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.sensei.search.req.protobuf.Hit)
  }
  
  public static final class Result extends
      com.google.protobuf.GeneratedMessage {
    // Use Result.newBuilder() to construct.
    private Result() {
      initFields();
    }
    private Result(boolean noInit) {}
    
    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }
    
    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Result_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sensei.search.req.protobuf.SenseiResultBPO.internal_static_com_sensei_search_req_protobuf_Result_fieldAccessorTable;
    }
    
    // optional uint32 numhits = 1;
    public static final int NUMHITS_FIELD_NUMBER = 1;
    private boolean hasNumhits;
    private int numhits_ = 0;
    public boolean hasNumhits() { return hasNumhits; }
    public int getNumhits() { return numhits_; }
    
    // optional uint32 totaldocs = 2;
    public static final int TOTALDOCS_FIELD_NUMBER = 2;
    private boolean hasTotaldocs;
    private int totaldocs_ = 0;
    public boolean hasTotaldocs() { return hasTotaldocs; }
    public int getTotaldocs() { return totaldocs_; }
    
    // repeated .com.sensei.search.req.protobuf.FacetContainer facetContainers = 3;
    public static final int FACETCONTAINERS_FIELD_NUMBER = 3;
    private java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer> facetContainers_ =
      java.util.Collections.emptyList();
    public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer> getFacetContainersList() {
      return facetContainers_;
    }
    public int getFacetContainersCount() { return facetContainers_.size(); }
    public com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer getFacetContainers(int index) {
      return facetContainers_.get(index);
    }
    
    // repeated .com.sensei.search.req.protobuf.Hit hits = 4;
    public static final int HITS_FIELD_NUMBER = 4;
    private java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Hit> hits_ =
      java.util.Collections.emptyList();
    public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Hit> getHitsList() {
      return hits_;
    }
    public int getHitsCount() { return hits_.size(); }
    public com.sensei.search.req.protobuf.SenseiResultBPO.Hit getHits(int index) {
      return hits_.get(index);
    }
    
    // optional uint64 time = 5;
    public static final int TIME_FIELD_NUMBER = 5;
    private boolean hasTime;
    private long time_ = 0L;
    public boolean hasTime() { return hasTime; }
    public long getTime() { return time_; }
    
    // required int64 tid = 6 [default = -1];
    public static final int TID_FIELD_NUMBER = 6;
    private boolean hasTid;
    private long tid_ = -1L;
    public boolean hasTid() { return hasTid; }
    public long getTid() { return tid_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTid) return false;
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer element : getFacetContainersList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Hit element : getHitsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasNumhits()) {
        output.writeUInt32(1, getNumhits());
      }
      if (hasTotaldocs()) {
        output.writeUInt32(2, getTotaldocs());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer element : getFacetContainersList()) {
        output.writeMessage(3, element);
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Hit element : getHitsList()) {
        output.writeMessage(4, element);
      }
      if (hasTime()) {
        output.writeUInt64(5, getTime());
      }
      if (hasTid()) {
        output.writeInt64(6, getTid());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNumhits()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getNumhits());
      }
      if (hasTotaldocs()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getTotaldocs());
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer element : getFacetContainersList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      for (com.sensei.search.req.protobuf.SenseiResultBPO.Hit element : getHitsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      if (hasTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, getTime());
      }
      if (hasTid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getTid());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.sensei.search.req.protobuf.SenseiResultBPO.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.sensei.search.req.protobuf.SenseiResultBPO.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.sensei.search.req.protobuf.SenseiResultBPO.Result result;
      
      // Construct using com.sensei.search.req.protobuf.SenseiResultBPO.Result.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.sensei.search.req.protobuf.SenseiResultBPO.Result();
        return builder;
      }
      
      protected com.sensei.search.req.protobuf.SenseiResultBPO.Result internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.sensei.search.req.protobuf.SenseiResultBPO.Result();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Result.getDescriptor();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Result getDefaultInstanceForType() {
        return com.sensei.search.req.protobuf.SenseiResultBPO.Result.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.Result build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.sensei.search.req.protobuf.SenseiResultBPO.Result buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.sensei.search.req.protobuf.SenseiResultBPO.Result buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.facetContainers_ != java.util.Collections.EMPTY_LIST) {
          result.facetContainers_ =
            java.util.Collections.unmodifiableList(result.facetContainers_);
        }
        if (result.hits_ != java.util.Collections.EMPTY_LIST) {
          result.hits_ =
            java.util.Collections.unmodifiableList(result.hits_);
        }
        com.sensei.search.req.protobuf.SenseiResultBPO.Result returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sensei.search.req.protobuf.SenseiResultBPO.Result) {
          return mergeFrom((com.sensei.search.req.protobuf.SenseiResultBPO.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.sensei.search.req.protobuf.SenseiResultBPO.Result other) {
        if (other == com.sensei.search.req.protobuf.SenseiResultBPO.Result.getDefaultInstance()) return this;
        if (other.hasNumhits()) {
          setNumhits(other.getNumhits());
        }
        if (other.hasTotaldocs()) {
          setTotaldocs(other.getTotaldocs());
        }
        if (!other.facetContainers_.isEmpty()) {
          if (result.facetContainers_.isEmpty()) {
            result.facetContainers_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer>();
          }
          result.facetContainers_.addAll(other.facetContainers_);
        }
        if (!other.hits_.isEmpty()) {
          if (result.hits_.isEmpty()) {
            result.hits_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Hit>();
          }
          result.hits_.addAll(other.hits_);
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setNumhits(input.readUInt32());
              break;
            }
            case 16: {
              setTotaldocs(input.readUInt32());
              break;
            }
            case 26: {
              com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.Builder subBuilder = com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFacetContainers(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.sensei.search.req.protobuf.SenseiResultBPO.Hit.Builder subBuilder = com.sensei.search.req.protobuf.SenseiResultBPO.Hit.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHits(subBuilder.buildPartial());
              break;
            }
            case 40: {
              setTime(input.readUInt64());
              break;
            }
            case 48: {
              setTid(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 numhits = 1;
      public boolean hasNumhits() {
        return result.hasNumhits();
      }
      public int getNumhits() {
        return result.getNumhits();
      }
      public Builder setNumhits(int value) {
        result.hasNumhits = true;
        result.numhits_ = value;
        return this;
      }
      public Builder clearNumhits() {
        result.hasNumhits = false;
        result.numhits_ = 0;
        return this;
      }
      
      // optional uint32 totaldocs = 2;
      public boolean hasTotaldocs() {
        return result.hasTotaldocs();
      }
      public int getTotaldocs() {
        return result.getTotaldocs();
      }
      public Builder setTotaldocs(int value) {
        result.hasTotaldocs = true;
        result.totaldocs_ = value;
        return this;
      }
      public Builder clearTotaldocs() {
        result.hasTotaldocs = false;
        result.totaldocs_ = 0;
        return this;
      }
      
      // repeated .com.sensei.search.req.protobuf.FacetContainer facetContainers = 3;
      public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer> getFacetContainersList() {
        return java.util.Collections.unmodifiableList(result.facetContainers_);
      }
      public int getFacetContainersCount() {
        return result.getFacetContainersCount();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer getFacetContainers(int index) {
        return result.getFacetContainers(index);
      }
      public Builder setFacetContainers(int index, com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.facetContainers_.set(index, value);
        return this;
      }
      public Builder setFacetContainers(int index, com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.Builder builderForValue) {
        result.facetContainers_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFacetContainers(com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.facetContainers_.isEmpty()) {
          result.facetContainers_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer>();
        }
        result.facetContainers_.add(value);
        return this;
      }
      public Builder addFacetContainers(com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.Builder builderForValue) {
        if (result.facetContainers_.isEmpty()) {
          result.facetContainers_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer>();
        }
        result.facetContainers_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFacetContainers(
          java.lang.Iterable<? extends com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer> values) {
        if (result.facetContainers_.isEmpty()) {
          result.facetContainers_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer>();
        }
        super.addAll(values, result.facetContainers_);
        return this;
      }
      public Builder clearFacetContainers() {
        result.facetContainers_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .com.sensei.search.req.protobuf.Hit hits = 4;
      public java.util.List<com.sensei.search.req.protobuf.SenseiResultBPO.Hit> getHitsList() {
        return java.util.Collections.unmodifiableList(result.hits_);
      }
      public int getHitsCount() {
        return result.getHitsCount();
      }
      public com.sensei.search.req.protobuf.SenseiResultBPO.Hit getHits(int index) {
        return result.getHits(index);
      }
      public Builder setHits(int index, com.sensei.search.req.protobuf.SenseiResultBPO.Hit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hits_.set(index, value);
        return this;
      }
      public Builder setHits(int index, com.sensei.search.req.protobuf.SenseiResultBPO.Hit.Builder builderForValue) {
        result.hits_.set(index, builderForValue.build());
        return this;
      }
      public Builder addHits(com.sensei.search.req.protobuf.SenseiResultBPO.Hit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.hits_.isEmpty()) {
          result.hits_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Hit>();
        }
        result.hits_.add(value);
        return this;
      }
      public Builder addHits(com.sensei.search.req.protobuf.SenseiResultBPO.Hit.Builder builderForValue) {
        if (result.hits_.isEmpty()) {
          result.hits_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Hit>();
        }
        result.hits_.add(builderForValue.build());
        return this;
      }
      public Builder addAllHits(
          java.lang.Iterable<? extends com.sensei.search.req.protobuf.SenseiResultBPO.Hit> values) {
        if (result.hits_.isEmpty()) {
          result.hits_ = new java.util.ArrayList<com.sensei.search.req.protobuf.SenseiResultBPO.Hit>();
        }
        super.addAll(values, result.hits_);
        return this;
      }
      public Builder clearHits() {
        result.hits_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint64 time = 5;
      public boolean hasTime() {
        return result.hasTime();
      }
      public long getTime() {
        return result.getTime();
      }
      public Builder setTime(long value) {
        result.hasTime = true;
        result.time_ = value;
        return this;
      }
      public Builder clearTime() {
        result.hasTime = false;
        result.time_ = 0L;
        return this;
      }
      
      // required int64 tid = 6 [default = -1];
      public boolean hasTid() {
        return result.hasTid();
      }
      public long getTid() {
        return result.getTid();
      }
      public Builder setTid(long value) {
        result.hasTid = true;
        result.tid_ = value;
        return this;
      }
      public Builder clearTid() {
        result.hasTid = false;
        result.tid_ = -1L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.sensei.search.req.protobuf.Result)
    }
    
    static {
      defaultInstance = new Result(true);
      com.sensei.search.req.protobuf.SenseiResultBPO.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.sensei.search.req.protobuf.Result)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sensei_search_req_protobuf_Facet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sensei_search_req_protobuf_Facet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sensei_search_req_protobuf_FacetContainer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sensei_search_req_protobuf_FacetContainer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sensei_search_req_protobuf_FieldVal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sensei_search_req_protobuf_FieldVal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sensei_search_req_protobuf_Hit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sensei_search_req_protobuf_Hit_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sensei_search_req_protobuf_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_sensei_search_req_protobuf_Result_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020sensei-res.proto\022\036com.sensei.search.re" +
      "q.protobuf\"#\n\005Facet\022\013\n\003val\030\001 \002(\t\022\r\n\005coun" +
      "t\030\002 \001(\r\"U\n\016FacetContainer\022\014\n\004name\030\001 \002(\t\022" +
      "5\n\006facets\030\002 \003(\0132%.com.sensei.search.req." +
      "protobuf.Facet\"&\n\010FieldVal\022\014\n\004name\030\001 \002(\t" +
      "\022\014\n\004vals\030\002 \003(\t\"b\n\003Hit\022\r\n\005docid\030\001 \001(\r\022\r\n\005" +
      "score\030\002 \001(\002\022=\n\013fieldValues\030\003 \003(\0132(.com.s" +
      "ensei.search.req.protobuf.FieldVal\"\307\001\n\006R" +
      "esult\022\017\n\007numhits\030\001 \001(\r\022\021\n\ttotaldocs\030\002 \001(" +
      "\r\022G\n\017facetContainers\030\003 \003(\0132..com.sensei.",
      "search.req.protobuf.FacetContainer\0221\n\004hi" +
      "ts\030\004 \003(\0132#.com.sensei.search.req.protobu" +
      "f.Hit\022\014\n\004time\030\005 \001(\004\022\017\n\003tid\030\006 \002(\003:\002-1B3\n\036" +
      "com.sensei.search.req.protobufB\017SenseiRe" +
      "sultBPOH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_sensei_search_req_protobuf_Facet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_sensei_search_req_protobuf_Facet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sensei_search_req_protobuf_Facet_descriptor,
              new java.lang.String[] { "Val", "Count", },
              com.sensei.search.req.protobuf.SenseiResultBPO.Facet.class,
              com.sensei.search.req.protobuf.SenseiResultBPO.Facet.Builder.class);
          internal_static_com_sensei_search_req_protobuf_FacetContainer_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_sensei_search_req_protobuf_FacetContainer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sensei_search_req_protobuf_FacetContainer_descriptor,
              new java.lang.String[] { "Name", "Facets", },
              com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.class,
              com.sensei.search.req.protobuf.SenseiResultBPO.FacetContainer.Builder.class);
          internal_static_com_sensei_search_req_protobuf_FieldVal_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_sensei_search_req_protobuf_FieldVal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sensei_search_req_protobuf_FieldVal_descriptor,
              new java.lang.String[] { "Name", "Vals", },
              com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.class,
              com.sensei.search.req.protobuf.SenseiResultBPO.FieldVal.Builder.class);
          internal_static_com_sensei_search_req_protobuf_Hit_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_sensei_search_req_protobuf_Hit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sensei_search_req_protobuf_Hit_descriptor,
              new java.lang.String[] { "Docid", "Score", "FieldValues", },
              com.sensei.search.req.protobuf.SenseiResultBPO.Hit.class,
              com.sensei.search.req.protobuf.SenseiResultBPO.Hit.Builder.class);
          internal_static_com_sensei_search_req_protobuf_Result_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_sensei_search_req_protobuf_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_sensei_search_req_protobuf_Result_descriptor,
              new java.lang.String[] { "Numhits", "Totaldocs", "FacetContainers", "Hits", "Time", "Tid", },
              com.sensei.search.req.protobuf.SenseiResultBPO.Result.class,
              com.sensei.search.req.protobuf.SenseiResultBPO.Result.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
